name: Bug report
description: Report an issue in documentation, research artifacts, or code.
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue.

        This repository may contain documentation, research artifacts, and/or code. Please fill only the sections that apply.
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What kind of issue is this?
      options:
        - Documentation / text
        - Research artifact (notes, protocol, datasets, results)
        - Code
        - CI / automation
        - Other
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the problem?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Affected files or sections
      description: Link to the relevant files/sections (paths, headings, anchors).
      placeholder: |
        Examples:
        - docs/overview/mission-scope.md (section "Scope")
        - research/experiments/protocol.md
        - src/module/file.py
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce (if applicable)
      description: Provide a minimal, ordered list of steps for reproducibility (especially for code and research issues).
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to be true/correct?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What is actually true/observed?
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Evidence / references (research & docs)
      description: Cite sources, links, quotes (short), or reasoning that support the expected behavior.
      placeholder: |
        - Source (link / DOI / paper):
        - Screenshot (if applicable):
        - Quote (keep it short):
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Relevant versions, OS, and runtime details (mostly for code/CI issues).
      placeholder: |
        - OS:
        - Browser (if applicable):
        - Runtime:
        - Commit SHA / Tag:
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste logs (redact secrets) or attach screenshots.
      render: shell
    validations:
      required: false
