name: Feature request
description: Suggest an improvement to documentation, research artifacts, tooling, or code.
title: "feature: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement.

        Please focus on the problem and the user value first.
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What area does this request impact?
      options:
        - Documentation / text
        - Research artifact (notes, protocol, datasets, results)
        - Code
        - CI / automation
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the pain point and who it affects.
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Acceptance criteria
      description: What does "done" look like? List concrete, checkable outcomes.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
      placeholder: A high-level description is fine. Include UX/API shape if relevant.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References / evidence
      description: Links to official docs, papers, issues, examples, or prior art.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches have you considered?
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks and security considerations
      description: Potential downsides, trade-offs, or security implications.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, references, screenshots, or examples.
    validations:
      required: false
